spring:
  application:
    name: medilab-department-service
  profiles:
    active: dev
server:
  port: 9098
  tomcat:
    connection-timeout: 180000
      
springdoc:
  swagger-ui:
    enabled: true
    path: /department-doc.html
  api-docs:
    enabled: true
    path: /department-api
user: 
 data:
  duplicate: 
    message: The Data submitted may have already existed. Please check the data and submit once again
---
spring:
  profiles: dev
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    #url: jdbc:mysql://localhost:30306/medilab-department-service
    url: jdbc:${DB_PROTOCOL:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:medilab-department-service}
    username: ${DB_USER_NAME:root}
    password: ${DB_USER_PASSWORD:root}
  jpa:
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: stage
  h2:
    console:
      enabled: false
      path: /h2Console
